project:
  type: website
  output-dir: _site

website:
  title: "T20 Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: players.qmd
        text: Players
      - href: leagues.qmd
        text: Leagues

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
